name: Build CLI
description: Build the Hypha CLI binary

inputs:
  working-directory:
    description: 'Directory containing Cargo.toml'
    required: false
    default: 'cli'
  rust-target:
    description: 'Rust target triple for cross-compilation'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: ${{ inputs.rust-target }}
    
    - name: Build CLI
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        if [ -n "${{ inputs.rust-target }}" ]; then
          cargo build --release --target ${{ inputs.rust-target }} --verbose
        else
          cargo build --release --verbose
        fi
